version: '3'

services:
  bridge-gptr:
    build: .
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ./.env:/app/gpt-researcher/mcp-server/.env
    depends_on:
      - litellm

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "8000:8000"
    env_file:
      - ./litellm.env

networks:
  default:
    driver: bridge
