name: Build Open WebUI Image

on:
  push:
    branches: [ main ]
    paths:
      - 'open-webui/**'
      - '.gitmodules'
      - '.github/workflows/build-open-webui.yml'
  workflow_dispatch:
    inputs:
      commit:
        description: 'Specific commit hash to checkout'
        required: false
        default: ''
        type: string

env:
  REGISTRY: ghcr.io
  NAMESPACE: ai-cfia
  REPO: louis

jobs:
  build-open-webui:
    name: Build open-webui
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Initialize and update specific submodule
        run: git submodule update --init open-webui

      - name: Checkout specific submodule branch or commit
        run: |
          cd open-webui
          git fetch
          if [ -n "${{ github.event.inputs.commit }}" ]; then
            git checkout ${{ github.event.inputs.commit }}
          else
            git checkout louis-main
            git pull origin louis-main
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: List files in build context for debugging
        run: |
          echo "Listing root directory:"
          ls -la
          echo "Listing open-webui directory:"
          ls -la open-webui

      - name: Get submodule commit hash
        id: submodule
        run: |
          cd ./open-webui
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_OUTPUT

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPO }}
          tags: |
            type=raw,value=open-webui-louis-main
            type=raw,value=open-webui-louis-${{ steps.submodule.outputs.COMMIT_HASH }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./open-webui
          file: ./open-webui/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 
